---
- hosts: Webservers
  become: yes
  tasks:
  - name: I want to install git on ubuntu
    apt:
      name: git
      state: present
    when: ansible_os_family =="Debian"

  - name: I want to install wget on ubuntu
    apt:
      name: wget
      state: present
    when: ansible_os_family =="Debian"  

  - name: I want to install wget on redhat
    yum:
      name: wget
      state: present
    when: ansible_os_family =="RedHat"  

  - name: I want to install apache2 webserver on redhat
    yum:
      name: "{{Myredhatapacheserver}}"
      state: present
    when: ansible_os_family =="RedHat"   

  - name: I want to start the webserver
    service:
      name: "{{Myredhatapacheserver}}"
      state: started
    when: ansible_os_family =="RedHat"  


  - name: I want to install apache2 server on ubuntu
    apt:
      name: "{{Myubuntuapacheserver}}"
      state: present
    when: ansible_os_family =="Debian"   

  - name: I want to install Java on ubuntu
    apt:
      name: "{{InstallMyJava}}"
      state: present
    when: ansible_os_family =="Debian"     


