---
- hosts: Webservers
  become: yes
  tasks:
  - name: I want to install git on ubuntu
    apt:
      name: git
      state: present
    when: ansible_os_family =="Debian"

  - name: I want to install wget on ubuntu
    apt:
      name: wget
      state: present
    when: ansible_os_family =="Debian"  

  - name: I want to install wget on redhat
    yum:
      name: wget
      state: present
    when: ansible_os_family =="RedHat"  

  - name: I want to install apache2 webserver on redhat
    yum:
      name: apache2
      state: present
    when: ansible_os_family ="Redhat"   


